spring:
  datasource:
    url: jdbc:mysql://34.126.155.222:3307/momun_api
    username: mnor
    password: 123@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8181